apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-01-08T17:24:37Z"
  generation: 1
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "10724409"
  uid: d66aa57c-6712-4fdf-8df8-7e89d580e1bb
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: myapp-worker
